# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Chris
tagline:
description:
url:              http://www.craftfortress.com

author:
  name:           'Chris'
  url:            https://twitter.com/craftfortress

paginate:         5

# Custom vars

github:
  repo:          https://github.com/craftfortress
